language: csharp
sudo: required
dist: trusty
mono: latest
dotnet: 2.0.0
os:
  - linux
cache:
  directories:
    - tools
before_cache:
  - rm -f tools/packages.config
git:
  depth: 1000
script:
  - chmod 755 ./build.sh
  - ./build.sh
